CadastroCliente.WebClient/Models/ErrorViewModel.cs
namespace CadastroCliente.WebClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroCliente.WebClient/Controllers/ClienteApiController.cs
using CadastroCliente.Domain.Filters;
using CadastroCliente.Domain.Repositories;
using CadastroCliente.Domain.Services.Clientes.Contracts;
using CadastroCliente.Domain.Services.Clientes.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace CadastroCliente.WebClient.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ClienteApiController : Controller
    {
        private readonly IClienteRepository _clienteRepository;
        private readonly IClienteService _clienteService;
        public ClienteApiController(
            IClienteRepository clienteRepository,
            IClienteService clienteService
        )
        {
            _clienteRepository = clienteRepository;
            _clienteService = clienteService;
        }

        [HttpGet]
        public async ValueTask<IActionResult> GetAll([FromQuery] ClienteFilter clienteFilter)
        {
            return Ok(await _clienteRepository.GetAll(clienteFilter));
        }

        [HttpGet("{id:guid}")]
        public async ValueTask<IActionResult> GetByid([FromRoute] Guid id)
        {
            var cliente = await _clienteRepository.GetAsync(x => x.Id == id);

            if (cliente is null) return NotFound();

            return Ok(cliente);
        }

        [HttpPost]
        public async ValueTask<IActionResult> Create([FromBody] ClienteDto clienteDto)
        {
            if (clienteDto is null) return UnprocessableEntity();

            return Ok(await _clienteService.CreateAsync(clienteDto));
        }
    }
}

CadastroCliente.WebClient/Controllers/ClienteController.cs
using CadastroCliente.Domain.Filters;
using CadastroCliente.Domain.Projections;
using CadastroCliente.Domain.Repositories;
using CadastroCliente.Domain.Services.Clientes.Contracts;
using CadastroCliente.Domain.Services.Clientes.Dtos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CadastroCliente.WebClient.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepository _clienteRepository;
        private readonly IClienteService _clienteService;
        public ClienteController(
            IClienteRepository clienteRepository,
            IClienteService clienteService
        )
        {
            _clienteRepository = clienteRepository;
            _clienteService = clienteService;
        }

        // GET: ClienteController1
        public async Task<ActionResult> Index(ClienteFilter clienteFilter)
        {
            return View((await _clienteRepository.GetAll(clienteFilter)).ToVm());
        }

        // GET: ClienteController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClienteController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClienteDto dto)
        {
            try
            {
                await _clienteService.CreateAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClienteController1/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var cliente = await _clienteRepository.GetAsync(x => x.Id == id);
            return View(new EditClienteDto
            {
                Id = cliente.Id,
                Nome = cliente.Nome,
                Cpf = cliente.Cpf.Number,
                BirthDate = cliente.BirthDate,
                Sexo = cliente.Sexo,
                Address = cliente.Address
            });
        }

        // POST: ClienteController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, EditClienteDto dto)
        {
            try
            {
                dto.Id = id;
                await _clienteService.EditAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View(e.Message);
            }
        }

        // GET: ClienteController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClienteController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id)
        {
            try
            {
                await _clienteRepository.DeleteAsync(await _clienteRepository.GetAsync(x => x.Id == id));
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CadastroCliente.WebClient/Controllers/HomeController.cs
using CadastroCliente.WebClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroCliente.WebClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroCliente.WebClient/Views/Cliente/Create.cshtml
@model CadastroCliente.Domain.Services.Clientes.Dtos.ClienteDto

@{
    ViewData["Title"] = "Novo Cliente";
}

<h1>Novo Cliente</h1>

<h4>Dados do Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>          
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input type="date" asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.State" class="control-label"></label>
                <input asp-for="Address.State" class="form-control" />
                <span asp-validation-for="Address.State" class="text-danger"></span>
            </div>
                 <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Feminino">Feminino</option>
                    <option value="Outros">Outros</option>
                </select>
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroCliente.WebClient/Views/Cliente/Delete.cshtml
@model CadastroCliente.Domain.Services.Clientes.Dtos.ClienteDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<h3>Deseja realmente excluir este registro?</h3>
<div>    
    <form asp-action="Delete" >
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

CadastroCliente.WebClient/Views/Cliente/Edit.cshtml
@model CadastroCliente.Domain.Services.Clientes.Dtos.EditClienteDto

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Dados do Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input type="hidden" asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input type="date" asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.State" class="control-label"></label>
                <input asp-for="Address.State" class="form-control" />
                <span asp-validation-for="Address.State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.Street" class="control-label"></label>
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <select asp-for="Sexo" class="form-control">
                    <option value="Masculino">Masculino</option>
                    <option value="Feminino">Feminino</option>
                    <option value="Outros">Outros</option>
                </select>
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroCliente.WebClient/Views/Cliente/Index.cshtml
@model IEnumerable<CadastroCliente.Domain.ViewModels.ClienteViewModel>

@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Create">Novo Cliente</a>
</p>
<div>
    <form method="get" asp-action="Index" asp-controller="Cliente">
        <div class="row">
            <div class="col-md-6"> 
                <div class="form-group">
                    <label class="control-label">Nome</label>
                    <input name="Nome" class="form-control" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Data de Nascimento</label>
                    <input type="date" name="BirthDate" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Cpf</label>
                    <input name="Cpf" class="form-control" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <input name="State" class="form-control" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Cidade</label>
                    <input name="City" class="form-control" />
                </div>
            </div>
            <div class="col-md-6">
               <label class="control-label">Sexo</label>
                <select name="Sexo" class="form-control">
                    <option>Selecione:</option>
                    <option value="Masculino">Masculino</option>
                    <option value="Feminino">Feminino</option>
                    <option value="Outros">Outros</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Pesquisar" class="btn btn-primary" />
        </div>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Nome
                </td>
                <td>
                    @item.BirthDate.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @item.Cpf?.Formatted
                </td>
                <td>
                    @item.Sexo
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id  }) |
                    @Html.ActionLink("Excluir", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

CadastroCliente.WebClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadastroCliente.WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadastro Cliente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroCliente.WebClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CadastroCliente.WebClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>